In [2]:
#Zadanie 1 Pandas

import pandas
import numpy

mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = numpy.arange(26)
mydict = dict(zip(mylist, myarr))

series_list = pandas.Series(mylist)
series_array = pandas.Series(myarr)
series_dict = pandas.Series(mydict)

print("\n Lista:")
print(series_list)

print("\n Tablica:")
print(series_array)

print("\n Słownik:")
print(series_dict)


 Lista:
0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

 Tablica:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int32

 Słownik:
a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int32


In [4]:
# Zadanie 2 Pandas

import pandas

data = {
    "Imię": ["Alicja", "Krzysztof", "Karol"],
    "Nazwisko": ["Strzelec", "Kowalski", "Lewandowski"],
    "Wiek": [33, 20, 21]
}

df = pandas.DataFrame(data)
print("DataFrame:")
print(df)

DataFrame:
        Imię     Nazwisko  Wiek
0     Alicja     Strzelec    33
1  Krzysztof     Kowalski    20
2      Karol  Lewandowski    21


In [6]:
# Zadanie 3 Pandas

import pandas

data = {
    "nr rejestru": [2, 4, 6, 8, 10, 12, 14],
    "miasto wojewódzkie": [
        "Wrocław",
        "Bydgoszcz / Toruń",
        "Lublin",
        "Gorzów Wielkopolski / Zielona Góra",
        "Łódź",
        "Kraków",
        "Warszawa"
    ],
    "powierzchnia [km²]": [19946.70, 17971.34, 25122.46, 13987.93, 18218.95, 15182.79, 35558.47],
    "ludność": [2904198, 2086210, 2139726, 1018084, 2493603, 3372618, 5349114]
}

wojewodztwa = [
    "dolnośląskie",
    "kujawsko-pomorskie",
    "lubelskie",
    "lubuskie",
    "łódzkie",
    "małopolskie",
    "mazowieckie"
]

df = pandas.DataFrame(data, index=wojewodztwa)
print("Obiekt DataFrame:")
print(df)

Obiekt DataFrame:
                    nr rejestru                  miasto wojewódzkie  \
dolnośląskie                  2                             Wrocław   
kujawsko-pomorskie            4                   Bydgoszcz / Toruń   
lubelskie                     6                              Lublin   
lubuskie                      8  Gorzów Wielkopolski / Zielona Góra   
łódzkie                      10                                Łódź   
małopolskie                  12                              Kraków   
mazowieckie                  14                            Warszawa   

                    powierzchnia [km²]  ludność  
dolnośląskie                  19946.70  2904198  
kujawsko-pomorskie            17971.34  2086210  
lubelskie                     25122.46  2139726  
lubuskie                      13987.93  1018084  
łódzkie                       18218.95  2493603  
małopolskie                   15182.79  3372618  
mazowieckie                   35558.47  5349114  


In [22]:
# Wyznacz miasta wojewódzkie w województwach o powierzchni mniejszej niż 20000 km²

filtered_df = df[df['powierzchnia [km²]'] < 20000]
print("Miasta wojewódzkie w województwach o powierzchni mniejszej niż 20000 km²:")
print(filtered_df['miasto wojewódzkie'])

Miasta wojewódzkie w województwach o powierzchni mniejszej niż 20000 km²:
dolnośląskie                                     Wrocław
kujawsko-pomorskie                     Bydgoszcz / Toruń
lubuskie              Gorzów Wielkopolski / Zielona Góra
łódzkie                                             Łódź
małopolskie                                       Kraków
Name: miasto wojewódzkie, dtype: object


In [17]:
# Utwórz nowy obiekt DataFrame zawierający województwa w których liczba ludności przekracza 2000000

filtered_df = df[df['ludność'] > 2000000]
print("Województwa, w których liczba ludności przekracza 2 miliony:")
print(filtered_df)

Województwa, w których liczba ludności przekracza 2 miliony:
                    nr rejestru miasto wojewódzkie  powierzchnia [km²]  \
dolnośląskie                  2            Wrocław            19946.70   
kujawsko-pomorskie            4  Bydgoszcz / Toruń            17971.34   
lubelskie                     6             Lublin            25122.46   
łódzkie                      10               Łódź            18218.95   
małopolskie                  12             Kraków            15182.79   
mazowieckie                  14           Warszawa            35558.47   

                    ludność  
dolnośląskie        2904198  
kujawsko-pomorskie  2086210  
lubelskie           2139726  
łódzkie             2493603  
małopolskie         3372618  
mazowieckie         5349114  


In [19]:
# Dodaj wiersz: wielkopolskie 30 Poznań 29 826,50 3 475 323

new = {
    "nr rejestru": 30,
    "miasto wojewódzkie": "Poznań",
    "powierzchnia [km²]": 29826.50,
    "ludność": 3475323
}

df.loc["wielkopolskie"] = new
print("DataFrame po dodaniu województwa wielkopolskiego:")
print(df)

DataFrame po dodaniu województwa wielkopolskiego:
                    nr rejestru                  miasto wojewódzkie  \
dolnośląskie                  2                             Wrocław   
kujawsko-pomorskie            4                   Bydgoszcz / Toruń   
lubelskie                     6                              Lublin   
lubuskie                      8  Gorzów Wielkopolski / Zielona Góra   
łódzkie                      10                                Łódź   
małopolskie                  12                              Kraków   
mazowieckie                  14                            Warszawa   
wielkopolskie                30                              Poznań   

                    powierzchnia [km²]  ludność  
dolnośląskie                  19946.70  2904198  
kujawsko-pomorskie            17971.34  2086210  
lubelskie                     25122.46  2139726  
lubuskie                      13987.93  1018084  
łódzkie                       18218.95  2493603  
małopolski

In [21]:
# Posortuj dane po liczbie ludności malejąco

sorted_df = df.sort_values(by="ludność", ascending=False)
print("DataFrame po posortowaniu po liczbie ludności malejąco:")
print(sorted_df)

DataFrame po posortowaniu po liczbie ludności malejąco:
                    nr rejestru                  miasto wojewódzkie  \
mazowieckie                  14                            Warszawa   
wielkopolskie                30                              Poznań   
małopolskie                  12                              Kraków   
dolnośląskie                  2                             Wrocław   
łódzkie                      10                                Łódź   
lubelskie                     6                              Lublin   
kujawsko-pomorskie            4                   Bydgoszcz / Toruń   
lubuskie                      8  Gorzów Wielkopolski / Zielona Góra   

                    powierzchnia [km²]  ludność  
mazowieckie                   35558.47  5349114  
wielkopolskie                 29826.50  3475323  
małopolskie                   15182.79  3372618  
dolnośląskie                  19946.70  2904198  
łódzkie                       18218.95  2493603  
lube

In [25]:
# Przesuń kolumnę “miasto wojewódzkie” na ostatnie miejsce

cols = [col for col in sorted_df.columns if col != "miasto wojewódzkie"] + ["miasto wojewódzkie"]
sorted_df = sorted_df[cols]

print("DataFrame po przesunięciu kolumny 'miasto wojewódzkie' na ostatnie miejsce:")
print(sorted_df)

DataFrame po przesunięciu kolumny 'miasto wojewódzkie' na ostatnie miejsce:
                    nr rejestru  powierzchnia [km²]  ludność  \
mazowieckie                  14            35558.47  5349114   
wielkopolskie                30            29826.50  3475323   
małopolskie                  12            15182.79  3372618   
dolnośląskie                  2            19946.70  2904198   
łódzkie                      10            18218.95  2493603   
lubelskie                     6            25122.46  2139726   
kujawsko-pomorskie            4            17971.34  2086210   
lubuskie                      8            13987.93  1018084   

                                    miasto wojewódzkie  
mazowieckie                                   Warszawa  
wielkopolskie                                   Poznań  
małopolskie                                     Kraków  
dolnośląskie                                   Wrocław  
łódzkie                                           Łódź  
lubel

In [27]:
# Zmodyfikuj nazwy województw tak aby zaczynały się wielka literą

sorted_df.index = sorted_df.index.str.title()
print("DataFrame po modyfikacji nazw województw:")
print(sorted_df)

DataFrame po modyfikacji nazw województw:
                    nr rejestru  powierzchnia [km²]  ludność  \
Mazowieckie                  14            35558.47  5349114   
Wielkopolskie                30            29826.50  3475323   
Małopolskie                  12            15182.79  3372618   
Dolnośląskie                  2            19946.70  2904198   
Łódzkie                      10            18218.95  2493603   
Lubelskie                     6            25122.46  2139726   
Kujawsko-Pomorskie            4            17971.34  2086210   
Lubuskie                      8            13987.93  1018084   

                                    miasto wojewódzkie  
Mazowieckie                                   Warszawa  
Wielkopolskie                                   Poznań  
Małopolskie                                     Kraków  
Dolnośląskie                                   Wrocław  
Łódzkie                                           Łódź  
Lubelskie                              

In [20]:
# Utwórz obiekt typu series zawierający nazwy województw w indeksie i wartość logiczną oznaczającą czy średnia liczba ludności na km² przekracza 140

df['ludność na km²'] = df['ludność'] / df['powierzchnia [km²]']
result = df['ludność na km²'] > 140
print("Series z wartościami logicznymi dotyczącymi średniej liczby ludności na km²:")
print(result)

Series z wartościami logicznymi dotyczącymi średniej liczby ludności na km²:
dolnośląskie           True
kujawsko-pomorskie    False
lubelskie             False
lubuskie              False
łódzkie               False
małopolskie            True
mazowieckie            True
Name: ludność na km², dtype: bool


In [37]:
# Usuń wiersz zawierający woj. Lubuskie

df_without_lubuskie = df.drop("lubuskie")
print("DataFrame po usunięciu województwa 'lubuskie':")
print(df_without_lubuskie)

DataFrame po usunięciu województwa 'lubuskie':
                    nr rejestru miasto wojewódzkie  powierzchnia [km²]  \
dolnośląskie                  2            Wrocław            19946.70   
kujawsko-pomorskie            4  Bydgoszcz / Toruń            17971.34   
lubelskie                     6             Lublin            25122.46   
łódzkie                      10               Łódź            18218.95   
małopolskie                  12             Kraków            15182.79   
mazowieckie                  14           Warszawa            35558.47   
wielkopolskie                30             Poznań            29826.50   

                    ludność  ludność na km²  
dolnośląskie        2904198      145.597918  
kujawsko-pomorskie  2086210      116.085389  
lubelskie           2139726       85.171834  
łódzkie             2493603      136.868645  
małopolskie         3372618      222.134272  
mazowieckie         5349114      150.431501  
wielkopolskie       3475323      116.5

In [24]:
# Zastosuj funkcję pandas.DataFrame.describe() i wyznacz parametry statystyczne dla analizowanego zbioru danych

statystyki = df.describe()
print("Statystyki opisowe dla danych województw:")
print(statystyki)

Statystyki opisowe dla danych województw:
       nr rejestru  powierzchnia [km²]       ludność  ludność na km²
count     7.000000            7.000000  7.000000e+00        7.000000
mean      8.000000        20855.520000  2.766222e+06      132.724656
std       4.320494         7414.210715  1.356669e+06       49.365371
min       2.000000        13987.930000  1.018084e+06       72.783035
25%       5.000000        16577.065000  2.112968e+06      100.628612
50%       8.000000        18218.950000  2.493603e+06      136.868645
75%      11.000000        22534.580000  3.138408e+06      148.014710
max      14.000000        35558.470000  5.349114e+06      222.134272


In [8]:
# Zadanie 4 Pandas

import pandas
import numpy


data = {
    "Miasto": ["Warszawa", "Kraków", "Wrocław", "Poznań", "Gdańsk"],
    "Dzień 1": [6.33, numpy.nan, numpy.nan, numpy.nan, 7.10],
    "Dzień 2": [5.3, numpy.nan, 4.5, 6.1, 5.82],
    "Dzień 3": [numpy.nan, 7.31, 8.2, 0.3, numpy.nan],
    "Dzień 4": [2.2, 8.1, 2.4, 1.1, numpy.nan],
    "Dzień 5": [6.9, 6.5, 7.9, numpy.nan, 1.2]
}

cities = ["Warszawa", "Kraków", "Wrocław", "Poznań", "Gdańsk"]
df = pandas.DataFrame(data, index=cities)

print("DataFrame przed zamianą brakujących wartości:")
print(df)

print("\nBrakujące wartości (oznaczone jako True:")
print(df.isna())

df_filled = df.drop(columns="Miasto").apply(lambda col: col.fillna(col.mean()), axis=0)

df_filled["Miasto"] = df["Miasto"]

print("\nDataFrame po zamianie brakujących wartości na średnią:")
print(df_filled)

DataFrame przed zamianą brakujących wartości:
            Miasto  Dzień 1  Dzień 2  Dzień 3  Dzień 4  Dzień 5
Warszawa  Warszawa     6.33     5.30      NaN      2.2      6.9
Kraków      Kraków      NaN      NaN     7.31      8.1      6.5
Wrocław    Wrocław      NaN     4.50     8.20      2.4      7.9
Poznań      Poznań      NaN     6.10     0.30      1.1      NaN
Gdańsk      Gdańsk     7.10     5.82      NaN      NaN      1.2

Brakujące wartości (oznaczone jako True:
          Miasto  Dzień 1  Dzień 2  Dzień 3  Dzień 4  Dzień 5
Warszawa   False    False    False     True    False    False
Kraków     False     True     True    False    False    False
Wrocław    False     True    False    False    False    False
Poznań     False     True    False    False    False     True
Gdańsk     False    False    False     True     True    False

DataFrame po zamianie brakujących wartości na średnią:
          Dzień 1  Dzień 2  Dzień 3  Dzień 4  Dzień 5    Miasto
Warszawa    6.330     5.30     5.27 

In [10]:
#Zadanie 5 Pandas
import pandas
import numpy

# Utwórz listę 100 losowych liczb całkowitych
random_numbers = numpy.random.randint(1, 101, size=100)
df = pandas.DataFrame(random_numbers, columns=["Liczba"])


In [34]:
# Przekształć listę 1-wymiarową w listę 2-wymiarową o wymiarze 10x10

reshaped_array = random_numbers.reshape(10, 10)
print(reshaped_array)

[[66 82  9 48 68 19 75 93 50 49]
 [44 32 71 39 60 83 47 14 86 41]
 [47  5 46 36 57 47 17 28  3 93]
 [17 81  8  2 66 66  6 22 82 31]
 [11 32 46 97 50 75  5 41 31 56]
 [67 27 20 46 97  4 89 79 79 64]
 [10 78 65 57 85 84 13 54 63 24]
 [71 82 46 12 48 91 74 22 66 61]
 [23 11 57 33 29 85 91 24 55  9]
 [77 34 98 30 26 16 86 92 40 67]]


In [36]:
# Na podstawie powstałej macierzy utwórz obiekt DataFrame, jako indeks wierszy wykorzystaj kolejne litery alfabetu (a, b, ...), a jako indeks kolumn kolejne liczby (1, 2...)

import string

row_index = list(string.ascii_lowercase[:10])  # 'a' do 'j'
col_index = list(range(1, 11))
df = pandas.DataFrame(reshaped_array, index=row_index, columns=col_index)
print(df)

   1   2   3   4   5   6   7   8   9   10
a  66  82   9  48  68  19  75  93  50  49
b  44  32  71  39  60  83  47  14  86  41
c  47   5  46  36  57  47  17  28   3  93
d  17  81   8   2  66  66   6  22  82  31
e  11  32  46  97  50  75   5  41  31  56
f  67  27  20  46  97   4  89  79  79  64
g  10  78  65  57  85  84  13  54  63  24
h  71  82  46  12  48  91  74  22  66  61
i  23  11  57  33  29  85  91  24  55   9
j  77  34  98  30  26  16  86  92  40  67


In [38]:
# Utwórz nowy obiekt DataFrame zawierający co drugi wiersz i kolumny o indeksie większym niż 5

df_filtered = df.iloc[::2, 5:]
print("\nNowy DataFrame (co drugi wiersz i kolumny > 5):")
print(df_filtered)


Nowy DataFrame (co drugi wiersz i kolumny > 5):
   6   7   8   9   10
a  19  75  93  50  49
c  47  17  28   3  93
e  75   5  41  31  56
g  84  13  54  63  24
i  85  91  24  55   9


In [44]:
# Utwórz macierz zawierającą wartości true w komórkach odpowiadających wartościom logicznym z ramki danych utworzonej w poprzednim podpunkcie

df_boolean = df_filtered.apply(lambda x: x > 50)
print("Macierz logiczna (True dla wartości > 50):")
print(df_boolean)

Macierz logiczna (True dla wartości > 50):
      6      7      8      9      10
a  False   True   True  False  False
c  False  False  False  False   True
e   True  False  False  False   True
g   True  False   True   True  False
i   True   True  False   True  False
